Repository MyPet-Sparta5/Mypet-front, pull requests merged in 2024-07, with the labels that each got.

#5 [2024/07/22]feat/#3 main page
  package-lock.json
  package.json
  public/favicon.ico
  public/icon.ico
  public/icon용.png
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/assets/index_picture.png
  src/assets/logo.png
  src/components/Header.jsx
  src/index.js
  src/styles/App.css
  src/styles/Header.module.css
Labels: feat

#6 [2024/07/22]feat/#3 login front
  src/App.js
  src/components/Login.jsx
  src/pages/LoginPage.jsx
  src/styles/App.css
  src/styles/Login.module.css
Labels: feat

#9 [2024/07/22]feat/#7 signup front
  src/App.js
  src/components/Signup.jsx
  src/pages/SignupPage.jsx
  src/styles/Signup.module.css
Labels: feat

#10 [2024/07/22]feat/#8 posts front
  src/App.js
  src/components/PostList.jsx
  src/pages/PostListPage.jsx
  src/styles/PostList.module.css
Labels: feat

#13 [2024/07/23]feat/#11 freedom post front
  package-lock.json
  package.json
  src/App.js
  src/components/Comment.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
  src/context/PostContext.jsx
  src/pages/PostDetailPage.jsx
  src/styles/PostDetail.module.css
Labels: feat

#16 [2024/07/23]feat/#14 post edit modal
  src/components/PostDetail.jsx
  src/components/PostEditModal.jsx
  src/styles/Modal.module.css
Labels: feat

#17 [2024/07/23]feat/#15 post delete modal
  src/components/DeleteModal.jsx
  src/components/PostDetail.jsx
Labels: feat

#20 [2024/07/24]feat/#12 pet post detail
  package-lock.json
  package.json
  src/App.js
  src/components/DeleteModal.jsx
  src/components/ImageSlider.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
  src/components/ReportModal.jsx
  src/context/PostContext.jsx
  src/pages/PetCardPostPage.jsx
  src/styles/ImageSlider.module.css
  src/styles/Modal.module.css
  src/styles/PetCardPost.css
  src/styles/PostDetail.module.css
Labels: feat

#40 [#22]✨feat : 자랑하기 게시물 수정 모달 연결
  src/components/PetCardPost.jsx
Labels: feat

#41 [2024/07/24]feat/#23 pet post delete modal
  src/components/PetCardPost.jsx
Labels: feat

#46 [2024/07/25]feat/#21 user menu
  src/components/DropdownMenu.jsx
  src/components/Header.jsx
  src/styles/DropdownMenu.module.css
  src/styles/Header.module.css
Labels: feat

#47 [2024/07/25]feat/#35 posts back
  package-lock.json
  package.json
  set.Proxy.js
  src/App.js
  src/components/ImageSlider.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
  src/context/PostContext.jsx
Labels: feat

#48 [2024/07/25]feat/#2 kakao map api
  .gitignore
  public/index.html
  src/App.js
  src/components/Header.jsx
  src/pages/FacilityFinderPage.jsx
  src/styles/FacilityFinderPage.css
Labels: feat

#51 [2024/07/25]fix/#50 header css
  src/styles/Header.module.css
Labels: fix

#49 [2024/07/25]feat/#37 boast detail feat
  src/components/ImageSlider.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
Labels: feat

#56 [2024/07/25]refactor/#55-postList-css
  src/styles/PostList.module.css
Labels: refactor

#53 [2024/07/25] ✨ feat : 자랑,자유게시판 페이지 백앤드 연동
  src/App.js
  src/components/PostList.jsx
  src/pages/PostListPage.jsx
Labels: feat

#54 [2024/07/25]feat/#31 link signup backend
  src/components/Signup.jsx
Labels: feat

#59 [2024/07/25]feat/#45 reports backoffice front
  src/App.js
  src/components/AdminHeader.jsx
  src/components/ReportList.jsx
  src/pages/Admin/AdminReportListPage.jsx
  src/styles/PostList.module.css
  src/styles/ReportList.module.css
  src/styles/UserList.module.css
Labels: feat

#62 [2024/07/26] feat/#58 post create front
  src/components/PostCreateModal.jsx
  src/components/PostList.jsx
  src/styles/PostList.module.css
Labels: feat

#63 [2024/07/28]feat/#26 link login backend
  src/components/AdminHeader.jsx
  src/components/DropdownMenu.jsx
  src/components/Header.jsx
  src/components/Login.jsx
Labels: feat

#65 [2024/07/26] feat/#44 backoffice modal feat
  src/components/ReportList.jsx
  src/components/ReportStatusModal.jsx
  src/components/UserList.jsx
  src/components/UserRoleModal.jsx
  src/components/UserStatusModal.jsx
  src/styles/DropdownMenu.module.css
Labels: feat

#67 [2024/07/28]feat/#64 link logout backend
  src/components/DropdownMenu.jsx
  src/components/Logout.jsx
  src/components/refreshToken.jsx
  src/styles/DropdownMenu.module.css
Labels: feat

#70 [2024/07/28]feat/#66 게시물 작성 API 연동
  src/components/PostCreateModal.jsx
Labels: feat

#71 [2024/07/29]feat/#28 userpage backend
  src/components/UserList.jsx
  src/components/UserRoleModal.jsx
  src/components/UserStatusModal.jsx
  src/styles/UserList.module.css
Labels: feat

#72 [2024/07/29]feat/#27 comment
  src/components/PostDetail.jsx
  src/styles/PostDetail.module.css
Labels: feat

#74 [2024/07/29]feat/#68 post update back
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
Labels: feat

#77 [2024/07/29]feat/#30 post detail like
  src/components/LikeButton.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/styles/LikeButton.module.css
  src/styles/PostDetail.module.css
Labels: feat

#78 [2024/07/29]fix/#75 userList refreshToken
  src/components/UserList.jsx
Labels: fix

#79 [2024/07/29]feat/#69 post delete
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
Labels: feat

#81 [2024/07/29] feat/#80 user report backend
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/ReportModal.jsx
Labels: feat

#82 [2024/07/30]refactor/#73 auth refresh token
  src/components/LikeButton.jsx
  src/components/Login.jsx
  src/components/Logout.jsx
  src/components/PetCardPost.jsx
  src/components/PostCreateModal.jsx
  src/components/PostDetail.jsx
  src/components/UserList.jsx
  src/components/refreshToken.jsx
Labels: refactor

#84 [2024/07/30] fix/#83 Admin, Manager에 사용자 게시물 삭제 권한 부여
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
Labels: fix

#85 [2024/07/30]feat/#76 mypage front
  src/App.js
  src/components/ChangePasswordModal.jsx
  src/components/Profile.jsx
  src/components/UserEditModal.jsx
  src/components/WithdrawModal.jsx
  src/pages/ProfilePage.jsx
  src/styles/Modal.module.css
  src/styles/Profile.module.css
Labels: feat

#86 [2024/07/30]feat/#29 report page backend
  src/components/ReportList.jsx
  src/components/ReportStatusModal.jsx
  src/styles/ReportList.module.css
Labels: feat

#89 [2024/07/30]style/#88 modal style
  src/components/UserRoleModal.jsx
  src/components/UserStatusModal.jsx
  src/styles/Modal.module.css
Labels: style

#90 [2024/07/30]refactor/#87-update-refreshToken-filename
  src/components/RefreshToken.jsx
Labels: refactor

#92 [2024/07/30] fix/#91 postcreatemodal files
  src/components/PostCreateModal.jsx
  src/components/PostList.jsx
Labels: fix

#96 [2024/07/30]refactor/#95 AccessDeniedPage
  src/App.js
  src/ProtectedRoute.jsx
  src/pages/AccessDeniedPage.jsx
Labels: refactor

#97 [2024/07/30]fix/#93 userRole edit modal
  src/components/UserList.jsx
Labels: fix

#98 [2024/07/30]refactor /#94 post icon
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
Labels: refactor

#101 [2024/07/31]feat/#32 link mypage backend
  src/components/ChangePasswordModal.jsx
  src/components/DropdownMenu.jsx
  src/components/Logout.jsx
  src/components/Profile.jsx
  src/components/UserEditModal.jsx
  src/styles/Profile.module.css
Labels: feat

#102 [2024/07/31]refactor/#99 reportList nickname to email
  src/components/ReportList.jsx
  src/styles/ReportList.module.css
Labels: refactor

#104 [2024/07/31]fix/#103 profile user update
  src/components/DropdownMenu.jsx
  src/components/Profile.jsx
  src/styles/DropdownMenu.module.css
Labels: fix

#109 [2024/07/31]refactor/#105 post page refactor
  src/App.js
  src/components/MyPostList.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/Profile.jsx
  src/pages/MyPostListPage.jsx
  src/styles/Profile.module.css
Labels: refactor
