Repository MyPet-Sparta5/Mypet-front, pull requests merged in 2024-08, with the labels that each got.

#111 [2024/08/01]refactor/#110 admin header addNavigation
  src/App.js
  src/components/AdminHeader.jsx
  src/pages/Admin/AdminPostListPage.jsx
  src/pages/Admin/AdminSuspensionListPage.jsx
Labels: refactor

#115 [2024/08/01]feat/#113 admin post list
  src/components/AdminPostList.jsx
  src/pages/Admin/AdminPostListPage.jsx
  src/styles/PostList.module.css
Labels: feat

#116 [2024/08/01] feat/#114 admin post status modal
  src/components/AdminPostList.jsx
  src/components/PostStatusModal.jsx
  src/styles/PostList.module.css
Labels: feat

#117 [2024/08/01]feat/#112 user suspension list
  src/components/SuspensionList.jsx
  src/pages/Admin/AdminSuspensionListPage.jsx
  src/styles/SuspensionList.module.css
Labels: feat

#119 [2024/08/01]refactor /#118 report post id
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
Labels: refactor

#121 [#120]✨feat : adminpostList 연결
  src/components/AdminPostList.jsx
  src/components/PostDetail.jsx
  src/components/PostStatusModal.jsx
Labels: feat

#126 [2024/08/02]refactor/#125 adminPostList navigate edit
  src/components/AdminPostList.jsx
Labels: refactor

#127 [2024/08/02] refactor/#124 userlist report list edit
  src/components/ReportList.jsx
  src/components/UserList.jsx
Labels: refactor

#129 [2024/08/05]refactor/#128 user suspension issue
  src/components/UserList.jsx
  src/components/UserStatusModal.jsx
Labels: refactor

#131 [2024/08/05]refactor/#130 alert update user
  src/components/Login.jsx
  src/components/Signup.jsx
Labels: refactor

#133 [2024/08/05]refactor/#132 userList reportList userId
  src/components/ReportList.jsx
  src/components/UserList.jsx
  src/styles/ReportList.module.css
  src/styles/UserList.module.css
Labels: refactor

#135 [2024/08/06]refactor/#134 postListResponseDto
  src/components/AdminPostList.jsx
  src/components/PostList.jsx
Labels: refactor

#136 [2024/08/07]feat/#100 kakao login
  package-lock.json
  package.json
  src/App.js
  src/assets/kakao_login_medium_wide.png
  src/assets/kakaotalk_sharing_btn_small.png
  src/components/KakaoLinkCallback.jsx
  src/components/KakaoLoginCallback.jsx
  src/components/Login.jsx
  src/components/Profile.jsx
  src/components/Signup.jsx
  src/components/SocialAccountItem.jsx
  src/components/user/UserStorage.jsx
  src/styles/Login.module.css
  src/styles/Profile.module.css
  src/styles/SocialAccountItem.module.css
Labels: feat

#139 [2024/08/07] #138 email bug fix
  src/components/Profile.jsx
Labels: bug

#141 [2024/08/08]refactor/#140 baseUrl Authorization Refreshtoken
  set.Proxy.js
  src/components/AdminPostList.jsx
  src/components/KakaoLinkCallback.jsx
  src/components/KakaoLoginCallback.jsx
  src/components/LikeButton.jsx
  src/components/Login.jsx
  src/components/Logout.jsx
  src/components/MyPostList.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
  src/components/Profile.jsx
  src/components/RefreshToken.jsx
  src/components/ReportList.jsx
  src/components/Signup.jsx
  src/components/SuspensionList.jsx
  src/components/UserList.jsx
  src/pages/FacilityFinderPage.jsx
  src/setting/api.js
Labels: refactor

#142 [2024/08/08]refactor/#137 separate profile information
  src/components/DropdownMenu.jsx
  src/components/Profile.jsx
  src/styles/Profile.module.css
Labels: refactor

#144 [2024/08/08]#143 signup page update
  src/components/Signup.jsx
  src/styles/Signup.module.css
Labels: feat

#146 [2024/08/08]fix/#145 imageslider
  src/components/ImageSlider.jsx
  src/styles/ImageSlider.module.css
Labels: fix

#148 [2024/08/09]feat/#147 backoffice userList search
  src/components/UserList.jsx
  src/styles/UserList.module.css
Labels: feat

#150 [2024/08/09]refactor/#149 post soft delete
  src/components/AdminPostList.jsx
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
  src/components/PostStatusModal.jsx
Labels: refactor

#154 [2024/08/12] feat/#151 backoffice postList search
  package-lock.json
  package.json
  src/components/AdminPostList.jsx
  src/index.css
  src/styles/PostList.module.css
Labels: feat

#157 [2024/08/12] feat/#155 loading
  package-lock.json
  package.json
  src/assets/Loading.gif
  src/components/PostList.jsx
  src/setting/Loading.js
  src/styles/Loading.module.css
Labels: feat

#158 [2024/08/12]feat/#106 google account
  src/App.js
  src/assets/google_login_medium_wide.png
  src/assets/kakao_login_medium_wide.png
  src/assets/web_light_sq_na@2x.png
  src/components/Login.jsx
  src/components/Profile.jsx
  src/components/Signup.jsx
  src/components/SocialAccountItem.jsx
  src/components/buttons/GoogleLoginButton.jsx
  src/components/buttons/KakaoLoginButton.jsx
  src/components/callback/GoogleLinkCallback.jsx
  src/components/callback/GoogleLoginCallback.jsx
  src/components/callback/KakaoLinkCallback.jsx
  src/components/callback/KakaoLoginCallback.jsx
  src/styles/Signup.module.css
  src/styles/SocialLoginButton.module.css
Labels: feat

#163 [2024/08/12] fix : 리버스 프록시 설정 추가
  package-lock.json
  package.json
  vercel.json
Labels: fix

#166 [2024/08/12]🔥 del : vercel.json 삭제
  vercel.json
Labels: fix

#170 [2024/08/13]feat/#156 postList search
  src/App.js
  src/components/MyPostList.jsx
  src/components/PostCreateModal.jsx
  src/components/PostList.jsx
  src/components/Profile.jsx
  src/pages/PostListPage.jsx
  src/styles/PostList.module.css
Labels: feat

#171 [2024/08/13]fix/#169 comment error
  src/components/PetCardPost.jsx
  src/components/PostDetail.jsx
Labels: fix

#173 [2024/08/13]fix/#172 signup alert
  src/components/Signup.jsx
Labels: fix

#174 [2024/08/13]feat/#152 backoffice reportList search
  src/components/ReportList.jsx
  src/styles/ReportList.module.css
Labels: feat

#175 [2024/08/13]fix/#108 improve map
  src/App.js
  src/pages/FacilityFinderPage.jsx
Labels: feat

#176 [2024/08/13]feat/#153 backoffice suspensionList search
  src/components/SuspensionList.jsx
  src/styles/SuspensionList.module.css
Labels: feat

#178 [2024/08/14]fix/#177 email verification
  src/components/Signup.jsx
Labels: fix

#181 [2024/08/14]feat/#179 footer
  src/App.js
  src/components/Footer.jsx
  src/styles/Footer.css
Labels: feat

#184 [2024/08/14]refactor/#182 file error
  src/components/PostCreateModal.jsx
Labels: refactor

#187 [2024/08/14]fix/#186 createmodal category active
  src/components/PostCreateModal.jsx
Labels: fix

#190 [2024/08/14]fix/#189 createmodal alert
  src/components/PostList.jsx
Labels: fix

#192 [2024/08/16] fix/#191 mypage delete post
  src/components/Profile.jsx
Labels: fix

#194 [2024/08/18]fix/#193 login alert
  src/components/Login.jsx
Labels: fix

#197 [2024/08/19]Fix/#196 comment limit
  src/components/Comment.jsx
  src/components/PostDetail.jsx
  src/components/PostList.jsx
  src/styles/PostDetail.module.css
Labels: fix

#199 [2024/08/19]feat/#198 kakao map marker overlay
  src/assets/default_img.png
  src/components/KakaoMapOverlay.jsx
  src/pages/FacilityFinderPage.jsx
  src/styles/KakaoMapOverlay.module.css
Labels: feat

#201 [2024/08/19]refactor/#200 social login button
  src/assets/kakao_login_medium_narrow.png
  src/components/Header.jsx
  src/components/Login.jsx
  src/components/buttons/GoogleLoginButton.jsx
  src/components/buttons/KakaoLoginButton.jsx
  src/styles/Login.module.css
  src/styles/SocialLoginButton.module.css
Labels: refactor

#203 [2024/08/19]refactor/#202 pet card post refactor
  src/components/PetCardPost.jsx
  src/styles/PetCardPost.css
Labels: refactor

#206 [2024/08/20]hotfix/#205 comment date
  src/components/Comment.jsx
Labels: fix

#207 [2024/08/20]hotfix/#205 comment timezone
  src/components/Comment.jsx
Labels: fix

#209 [2024/08/21]hotfix/#208 map location bug fix
  src/pages/FacilityFinderPage.jsx
  src/setting/Loading.js
Labels: fix

#211 [2024/08/22]hotfix/#210 mypostlist active
  src/components/MyPostList.jsx
Labels: fix
